Fix test-reporter

diff --git a/.github/workflows/build-test-publish-dotnet-app-component.yml b/.github/workflows/build-test-publish-dotnet-app-component.yml
--- a/.github/workflows/build-test-publish-dotnet-app-component.yml
+++ b/.github/workflows/build-test-publish-dotnet-app-component.yml
@@ -50,13 +50,13 @@ jobs:
         run: dotnet test --filter TestType!=Integration --logger "trx;LogFileName=test-results.trx"
       - 
         name: Test Report
-        uses: dorny/test-reporter@v1
-        if: always()
+        uses: dorny/test-reporter@v1.9.1
+        if: success() || failure()        # run this step even if previous step failed
         with:
           name: .NET tests
           path: "**/test-results.trx"                            
           reporter: dotnet-trx
-          fail-on-error: true
+          fail-on-error: false
       -
         name: Docker Build
         run: |
diff --git a/.github/workflows/dotnet-build-test-pack-push-default.yml b/.github/workflows/dotnet-build-test-pack-push-default.yml
--- a/.github/workflows/dotnet-build-test-pack-push-default.yml
+++ b/.github/workflows/dotnet-build-test-pack-push-default.yml
@@ -50,12 +50,12 @@ jobs:
         run: dotnet test --configuration Release --no-build --logger "trx;LogFileName=test-results.trx"
       - name: Test Report
         uses: dorny/test-reporter@v1.9.1
-        if: always()
+        if: success() || failure()        # run this step even if previous step failed
         with:
           name: .NET tests
           path: "**/test-results.trx"                            
           reporter: dotnet-trx
-          fail-on-error: true
+          fail-on-error: false
       - name: Paranoid NuGet package clean
         # For convenience we push *.nupkg later, so make sure the output folder is wiped, a paranoid move in case we re-use a runner?
         run: rm -rf ./nupkgs
